### PR TITLE
Update ldclient-js

### PR DESCRIPTION
**Pull request by Dnguye92**
This PR is to solve #111. [ldclient-js version 2.9.7](https://github.com/launchdarkly/js-client/releases/tag/2.9.7) was released to reduce the the frequency of how often this error is being thrown.

### CODE REVIEW

**Comment by Dnguye92** [comment]
> Hey @Dnguye92,
> it looks like you haven't signed our **C**ontributor **L**icense **A**greement, yet.
> 
> > The purpose of a CLA is to ensure that the guardian of a project's outputs has the necessary ownership or grants of rights over all contributions to allow them to distribute under the chosen license.
> > [Wikipedia](http://en.wikipedia.org/wiki/Contributor_License_Agreement)
> 
> You can read and sign our full Contributor License Agreement [here](https://truecar-cla-bot.herokuapp.com/claform).
> 
> Once you've signed reply with `[clabot:check]` to prove it.
> 
> Appreciation of efforts,
> 
> clabot

`[clabot:check]`

**Comment by Dnguye92** [comment]
[clabot:check]

**Comment by Dnguye92** [comment]
[clabot:check]

**Comment by sethbattin** [comment]
awesome, thanks @Dnguye92!  Apologies for the CLA bit; the lawyers demand it.

Are you able to test whether this is effective for your usage using your branch, or would you need some kind of test version published to npm?

**Comment by Dnguye92** [comment]
> awesome, thanks @Dnguye92! Apologies for the CLA bit; the lawyers demand it.
> 
> Are you able to test whether this is effective for your usage using your branch, or would you need some kind of test version published to npm?

@sethbattin I guess a test version?

**Comment by Dnguye92** [comment]
@sethbattin how do i go about getting this test version?

**Comment by sethbattin** [comment]
Apologies, i got distracted after merging and tagging that 4.1.0 version (because i did it wrongly for an npm publish).  But you can download it over here and switch to a local file install https://github.com/TrueCar/react-launch-darkly/releases/tag/v4.1.0

But like I said over on #111 , it's unlikely this will fix your issue because `ldclient-js` is actually a peer dependency.  So not only won't this update change anything, but you could have upgraded it in your own npm project at any time without submitting anything this this library.  😐 

Apologies again for the runaround; I misread the dev dependencies when i saw your original ticket.

**Pull request merged**
